# Generated by Django 3.1.3 on 2021-06-15 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projectsapp', '0002_auto_20210615_1723'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjectsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True)),
                ('file_name', models.CharField(max_length=100)),
                ('incidents', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=20)),
                ('observations', models.TextField()),
                ('FPIC_assignement', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('auth_user_id', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsapp.projects')),
                ('subjects_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjectsapp.subjects')),
            ],
            options={
                'verbose_name': 'measurement',
            },
        ),
    ]
