# Generated by Django 3.1.3 on 2021-06-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurementsapp', '0002_alter_measurements_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='file_name',
            field=models.FileField(blank=True, null=True, upload_to='main_web/documents/Measurements/'),
        ),
    ]
