# Generated by Django 3.1.3 on 2021-07-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurementsapp', '0003_auto_20210622_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='FPIC_assignement',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
