# Generated by Django 3.2.3 on 2021-08-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurementsapp', '0004_auto_20210727_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='FPIC_assignement',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='incidents',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20),
        ),
    ]
