# Generated by Django 3.1.3 on 2021-09-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurementsapp', '0005_auto_20210813_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='file_name',
            field=models.FileField(blank=True, null=True, upload_to='main_web/static/documents/Measurements/'),
        ),
    ]
