# Generated by Django 3.1.4 on 2021-04-06 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comorbidities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=20)),
                ('condition', models.CharField(choices=[('P', 'Patient'), ('H', 'Healthy')], max_length=20)),
                ('height', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('skin_color', models.CharField(choices=[('B', 'Black'), ('W', 'White'), ('Y', 'Yellow'), ('BR', 'Brown'), ('N', 'No info')], default='No info', max_length=20, null=True)),
                ('handedness', models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('N', 'No info')], default='No info', max_length=20)),
                ('scholar_level', models.CharField(choices=[('NI', 'No info'), ('N', 'No education'), ('PS', 'Pre school'), ('ES', 'Elementary school'), ('MS', 'Middle school'), ('HS', 'High school'), ('T', 'Technical'), ('G', 'Graduate'), ('PG', 'Post-Graduate')], default='No info', max_length=20)),
                ('telephone', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('additional_info', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('auth_user_id', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medical_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HC_number', models.IntegerField()),
                ('surgery', models.TextField(null=True)),
                ('clinical_outcomes', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comorbidities_ids', models.ManyToManyField(to='subjectsapp.Comorbidities')),
                ('diseases_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjectsapp.diseases')),
                ('subjects_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjectsapp.subjects')),
            ],
        ),
    ]
