# Generated by Django 3.1.4 on 2021-04-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjectsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
