# Generated by Django 3.2.3 on 2021-05-28 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjectsapp', '0003_auto_20210406_1819'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subjects',
            table='subjects',
        ),
    ]
