# Generated by Django 3.2.3 on 2021-06-04 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjectsapp', '0004_alter_subjects_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjects',
            options={'managed': False},
        ),
    ]
