# Generated by Django 3.2.3 on 2021-06-13 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjectsapp', '0005_alter_subjects_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_record',
            name='HC_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='medical_record',
            name='comorbidities_ids',
            field=models.ManyToManyField(null=True, to='subjectsapp.Comorbidities'),
        ),
        migrations.AlterField(
            model_name='medical_record',
            name='diseases_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjectsapp.diseases'),
        ),
    ]
