# Generated by Django 3.2.3 on 2021-06-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjectsapp', '0006_auto_20210613_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_record',
            name='HC_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
