# Generated by Django 3.1.3 on 2021-07-27 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjectsapp', '0008_alter_medical_record_hc_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_record',
            name='clinical_outcomes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medical_record',
            name='comorbidities_ids',
            field=models.ManyToManyField(blank=True, null=True, to='subjectsapp.Comorbidities'),
        ),
        migrations.AlterField(
            model_name='medical_record',
            name='diseases_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjectsapp.diseases'),
        ),
        migrations.AlterField(
            model_name='medical_record',
            name='surgery',
            field=models.TextField(blank=True, null=True),
        ),
    ]
