# Generated by Django 3.2.3 on 2021-08-13 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjectsapp', '0009_auto_20210727_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_record',
            name='comorbidities_ids',
            field=models.ManyToManyField(related_name='comorbidities', to='subjectsapp.Comorbidities'),
        ),
        migrations.AlterField(
            model_name='medical_record',
            name='diseases_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='subjectsapp.diseases'),
        ),
    ]
