# Generated by Django 3.1.4 on 2021-04-06 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aux_Systems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NIRS_Systems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('num_of_sources', models.IntegerField()),
                ('num_of_detectors', models.IntegerField()),
                ('wavelenghts', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('CAAE', models.CharField(max_length=30, null=True)),
                ('FPIC_file', models.FileField(null=True, upload_to='main_web/documents/FPIC/')),
                ('prin_investigator', models.CharField(max_length=100)),
                ('co_investigator', models.CharField(max_length=100, null=True)),
                ('optical_probe_details', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('auth_user_id', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('aux_systems_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsapp.aux_systems')),
                ('nirs_systems_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsapp.nirs_systems')),
            ],
        ),
    ]
