# Generated by Django 3.1.3 on 2021-06-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='CAAE',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='projects',
            name='FPIC_file',
            field=models.FileField(upload_to='main_web/documents/FPIC/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='co_investigator',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='optical_probe_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='prin_investigator',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
