# Generated by Django 3.2.3 on 2021-06-18 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='optical_probe_details',
            new_name='probe_details',
        ),
    ]
