# Generated by Django 3.1.3 on 2021-06-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0002_rename_optical_probe_details_projects_probe_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_file',
            field=models.FileField(null=True, upload_to='main_web/documents/Projects/'),
        ),
    ]
