# Generated by Django 3.1.3 on 2021-07-27 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0003_projects_project_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='CAAE',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='FPIC_file',
            field=models.FileField(blank=True, null=True, upload_to='main_web/documents/FPIC/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='aux_systems_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectsapp.aux_systems'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='co_investigator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='probe_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_file',
            field=models.FileField(blank=True, null=True, upload_to='main_web/documents/Projects/'),
        ),
    ]
