# Generated by Django 3.1.3 on 2021-09-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0004_auto_20210727_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='protocol_details',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
