# Generated by Django 3.1.3 on 2021-10-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0005_projects_protocol_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='FPIC_file',
            field=models.FileField(blank=True, null=True, upload_to='main_web/media/Projects/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_file',
            field=models.FileField(blank=True, null=True, upload_to='main_web/media/Projects/'),
        ),
    ]
