# Generated by Django 3.1.3 on 2021-07-27 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcenter', '0002_auto_20210727_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='content',
            new_name='conteudo',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='image',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='content',
            new_name='conteudo',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='image',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='title',
            new_name='titulo',
        ),
    ]
