# Generated by Django 3.1.3 on 2021-07-27 23:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appcenter', '0003_auto_20210727_2042'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='Datatable',
        ),
        migrations.AlterModelOptions(
            name='datatable',
            options={'verbose_name': 'datatable', 'verbose_name_plural': 'datatables'},
        ),
    ]
